apiVersion: v1
kind: Service
metadata:
  name: basic-service
spec:
  selector:
    app: basic-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000