apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
spec:
  selector:
    matchLabels:
      app: basic-app
  replicas: 2
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
        - name: basic-server
          image: sample-server-kubernetes
          ports:
            - containerPort: 3000
          imagePullPolicy: Never # Image should not be pulled